'use client';

import Link from 'next/link';
import { motion } from 'framer-motion';
import { Reveal } from '@/components/Reveal';

const SECTIONS = [
  {
    eyebrow: 'USING LARK',
    items: [
      {
        title: 'Lark is free to use',
        body: 'The core features (tuner, chord detector) are free and will remain free. Pro and Studio plans are optional upgrades. We will never retroactively paywall features that were free at the time you started using them.',
      },
      {
        title: 'Acceptable use',
        body: 'Use Lark to learn and play guitar. Do not use automated scripts to scrape, crawl, or stress-test the service. Do not attempt to abuse, reverse-engineer, or interfere with the AI coaching endpoints or any part of the infrastructure.',
      },
      {
        title: 'Account responsibility',
        body: 'You are responsible for activity that occurs under your account. Keep your login credentials secure and notify us immediately at hello@lark.coach if you suspect unauthorized access.',
      },
    ],
  },
  {
    eyebrow: 'AUDIO & PRIVACY',
    items: [
      {
        title: 'Audio is processed locally',
        body: 'All pitch detection and chord analysis runs entirely in your browser via the Web Audio API. Your audio is never recorded, transmitted to our servers, or stored in any form. The moment you close the tab, the audio stream ends.',
      },
      {
        title: 'AI coaching data',
        body: 'When you request AI coaching after a session, your session statistics (song title, per-note accuracy, totals) are sent to Anthropic to generate feedback. No audio is included. This data is not linked to your account.',
      },
    ],
  },
  {
    eyebrow: 'AI RESPONSES',
    items: [
      {
        title: 'Educational purposes only',
        body: 'AI coaching responses are generated by a language model for educational and motivational guidance. They are not a substitute for professional music instruction. Results may vary and responses may occasionally be incorrect or imprecise.',
      },
      {
        title: 'No guarantee of accuracy',
        body: 'We make reasonable efforts to ensure AI feedback is helpful and relevant to your playing. However, we cannot guarantee the accuracy, completeness, or fitness of AI-generated content for any specific musical goal.',
      },
    ],
  },
  {
    eyebrow: 'SERVICE CHANGES',
    items: [
      {
        title: 'We may modify the service',
        body: 'We reserve the right to update, modify, or discontinue any part of Lark at any time. For significant changes affecting paid features, we will provide at least 30 days notice via email.',
      },
      {
        title: 'We may update these terms',
        body: 'If we make material changes to these terms, we will notify you by email and update the "Last updated" date on this page. Continued use of Lark after changes take effect constitutes acceptance of the new terms.',
      },
    ],
  },
  {
    eyebrow: 'LEGAL',
    items: [
      {
        title: 'Governing law',
        body: 'These terms are governed by applicable laws. Any disputes will be resolved in the jurisdiction where Lark operates. We will always try to resolve issues informally first, so reach out to us before pursuing formal action.',
      },
      {
        title: 'Limitation of liability',
        body: 'Lark is provided "as is" without warranty of any kind. To the extent permitted by law, we are not liable for any indirect, incidental, or consequential damages arising from your use of the service.',
      },
      {
        title: 'Contact',
        body: 'For questions about these terms, email us at hello@lark.coach.',
      },
    ],
  },
];

export default function TermsPage() {
  return (
    <main>
      <section style={{ padding: '120px 24px 60px', textAlign: 'center', position: 'relative', overflow: 'hidden' }}>
        <div style={{
          position: 'absolute',
          width: 420, height: 420,
          borderRadius: '50%',
          background: 'radial-gradient(circle, rgba(var(--accent-rgb), 0.09) 0%, transparent 70%)',
          top: '-10%', right: '-12%',
          animation: 'float 15s ease-in-out infinite',
          pointerEvents: 'none',
        }} />
        <div style={{ maxWidth: 720, margin: '0 auto', position: 'relative' }}>
          <motion.p
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
            className="eyebrow"
            style={{ marginBottom: 24 }}
          >
            TERMS OF SERVICE
          </motion.p>
          <motion.h1
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.06, ease: [0.16, 1, 0.3, 1] }}
            style={{
              fontFamily: 'var(--font-mono)',
              fontSize: 'clamp(34px, 6vw, 56px)',
              fontWeight: 700,
              color: 'var(--text)',
              letterSpacing: '-0.025em',
              lineHeight: 1.06,
              marginBottom: 22,
            }}
          >
            The rules of the road.
          </motion.h1>
          <motion.p
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ duration: 0.55, delay: 0.16 }}
            style={{ fontSize: 16, color: 'var(--text3)', lineHeight: 1.6 }}
          >
            Plain language. No legalese. Use Lark to play guitar, not to break things.
          </motion.p>
          <motion.p
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ duration: 0.55, delay: 0.24 }}
            style={{
              fontSize: 12,
              color: 'var(--text3)',
              fontFamily: 'var(--font-mono)',
              letterSpacing: '0.06em',
              marginTop: 18,
            }}
          >
            Last updated: May 2026
          </motion.p>
        </div>
      </section>

      <section style={{ padding: '20px 24px 100px' }}>
        <div style={{ maxWidth: 760, margin: '0 auto' }}>
          {SECTIONS.map((section, si) => (
            <Reveal key={section.eyebrow} delay={si * 0.04}>
              <div style={{ marginBottom: 52 }}>
                <p className="eyebrow" style={{ marginBottom: 20 }}>{section.eyebrow}</p>
                <div style={{ display: 'flex', flexDirection: 'column', gap: 0 }}>
                  {section.items.map((item) => (
                    <div
                      key={item.title}
                      style={{
                        borderBottom: '0.5px solid var(--border)',
                        padding: '22px 0',
                      }}
                    >
                      <p style={{
                        fontFamily: 'var(--font-mono)',
                        fontSize: 14,
                        fontWeight: 700,
                        color: 'var(--text)',
                        letterSpacing: '-0.01em',
                        marginBottom: 8,
                      }}>
                        {item.title}
                      </p>
                      <p style={{
                        fontSize: 14,
                        color: 'var(--text2)',
                        lineHeight: 1.75,
                        maxWidth: 640,
                      }}>
                        {item.body}
                      </p>
                    </div>
                  ))}
                </div>
              </div>
            </Reveal>
          ))}
        </div>
      </section>

      <section style={{ padding: '40px 24px 140px', textAlign: 'center' }}>
        <Reveal>
          <p className="eyebrow" style={{ marginBottom: 18 }}>READY TO PLAY?</p>
          <h2 style={{
            fontFamily: 'var(--font-mono)',
            fontSize: 'clamp(22px, 4vw, 34px)',
            fontWeight: 700,
            color: 'var(--text)',
            letterSpacing: '-0.02em',
            lineHeight: 1.1,
            marginBottom: 16,
          }}>
            Let the guitar do the talking.
          </h2>
          <p style={{ fontSize: 14, color: 'var(--text3)', lineHeight: 1.65, marginBottom: 28 }}>
            Questions? Email{' '}
            <a
              href="mailto:hello@lark.coach"
              style={{ color: 'var(--accent)', textDecoration: 'none', fontFamily: 'var(--font-mono)', fontSize: 13 }}
            >
              hello@lark.coach
            </a>
            .
          </p>
          <div style={{ display: 'flex', gap: 12, justifyContent: 'center', flexWrap: 'wrap' }}>
            <Link href="/auth?mode=signup" className="btn btn-accent btn-lg">GET STARTED</Link>
            <Link href="/privacy" className="btn btn-outline btn-lg">PRIVACY POLICY</Link>
          </div>
        </Reveal>
      </section>
    </main>
  );
}
