'use client';

import Link from 'next/link';
import { motion } from 'framer-motion';
import { Reveal } from '@/components/Reveal';

const SECTIONS = [
  {
    eyebrow: 'Using Lark',
    items: [
      { title: 'Lark is free to use', body: 'The core features (tuner, chord detector) are free and will remain free. Pro and Studio plans are optional upgrades. We will never retroactively paywall features that were free at the time you started using them.' },
      { title: 'Acceptable use', body: 'Use Lark to learn and play guitar. Do not use automated scripts to scrape, crawl, or stress-test the service. Do not attempt to abuse, reverse-engineer, or interfere with the AI coaching endpoints or any part of the infrastructure.' },
      { title: 'Account responsibility', body: 'You are responsible for activity that occurs under your account. Keep your login credentials secure and notify us immediately at the404supply@gmail.com if you suspect unauthorized access.' },
    ],
  },
  {
    eyebrow: 'Audio & privacy',
    items: [
      { title: 'Audio is processed locally', body: 'All pitch detection and chord analysis runs entirely in your browser via the Web Audio API. Your audio is never recorded, transmitted to our servers, or stored in any form. The moment you close the tab, the audio stream ends.' },
      { title: 'AI coaching data', body: 'When you request AI coaching after a session, your session statistics (song title, per-note accuracy, totals) are sent to Anthropic to generate feedback. No audio is included. This data is not linked to your account.' },
    ],
  },
  {
    eyebrow: 'AI responses',
    items: [
      { title: 'Educational purposes only', body: 'AI coaching responses are generated by a language model for educational and motivational guidance. They are not a substitute for professional music instruction. Results may vary and responses may occasionally be incorrect or imprecise.' },
      { title: 'No guarantee of accuracy', body: 'We make reasonable efforts to ensure AI feedback is helpful and relevant to your playing. However, we cannot guarantee the accuracy, completeness, or fitness of AI-generated content for any specific musical goal.' },
    ],
  },
  {
    eyebrow: 'Service changes',
    items: [
      { title: 'We may modify the service', body: 'We reserve the right to update, modify, or discontinue any part of Lark at any time. For significant changes affecting paid features, we will provide at least 30 days notice via email.' },
      { title: 'We may update these terms', body: 'If we make material changes to these terms, we will notify you by email and update the "Last updated" date on this page. Continued use of Lark after changes take effect constitutes acceptance of the new terms.' },
    ],
  },
  {
    eyebrow: 'Legal',
    items: [
      { title: 'Governing law', body: 'These terms are governed by applicable laws. Any disputes will be resolved in the jurisdiction where Lark operates. We will always try to resolve issues informally first, so reach out to us before pursuing formal action.' },
      { title: 'Limitation of liability', body: 'Lark is provided "as is" without warranty of any kind. To the extent permitted by law, we are not liable for any indirect, incidental, or consequential damages arising from your use of the service.' },
      { title: 'Contact', body: 'For questions about these terms, email us at the404supply@gmail.com.' },
    ],
  },
];

export default function TermsPage() {
  return (
    <main>
      <section className="ed-section">
        <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5, ease: [0.16, 1, 0.3, 1] }}>
          <div className="ed-rule" />
          <div className="ed-head"><span className="ed-label">Terms of service</span></div>
          <h1 className="ed-title ed-title-sm">The rules<br />of the road.</h1>
          <p className="ed-lead">Plain language. No legalese. Use Lark to play guitar, not to break things.</p>
          <p className="ed-stamp">Last updated: May 2026</p>
        </motion.div>
      </section>

      <section className="ed-section" style={{ paddingTop: 'clamp(32px, 4vh, 48px)' }}>
        {SECTIONS.map((section, si) => (
          <Reveal key={section.eyebrow} delay={0.04}>
            <div style={{ marginTop: si === 0 ? 0 : 'clamp(48px, 7vh, 80px)' }}>
              <div className="ed-rule" />
              <div className="ed-head" style={{ marginBottom: 12 }}>
                <span className="ed-num">{String(si + 1).padStart(2, '0')}</span>
                <span className="ed-label">{section.eyebrow}</span>
              </div>
              <div style={{ maxWidth: 760 }}>
                {section.items.map(item => (
                  <div key={item.title} className="legal-item">
                    <p className="legal-title">{item.title}</p>
                    <p className="legal-body">{item.body}</p>
                  </div>
                ))}
              </div>
            </div>
          </Reveal>
        ))}
      </section>

      <section className="ed-section ed-section-pb" style={{ paddingTop: 'clamp(56px, 9vh, 104px)' }}>
        <Reveal>
          <div className="ed-rule" />
          <div className="ed-head"><span className="ed-label">Ready to play?</span></div>
          <h2 className="ed-title ed-title-sm">Let the guitar<br />do the talking.</h2>
          <p className="ed-lead">
            Questions? Email <a href="mailto:the404supply@gmail.com" className="legal-link">the404supply@gmail.com</a>.
          </p>
          <div style={{ display: 'flex', gap: 12, flexWrap: 'wrap', marginTop: 28 }}>
            <Link href="/auth?mode=signup" className="ed-btn ed-btn-accent ed-btn-lg">Get started</Link>
            <Link href="/privacy" className="ed-btn ed-btn-outline ed-btn-lg">Privacy policy</Link>
          </div>
        </Reveal>
      </section>

      <style jsx>{`
        .ed-stamp { font-family: var(--font-mono); font-size: 11px; font-weight: 700; letter-spacing: 0.12em; text-transform: uppercase; color: var(--text-muted); margin-top: 22px; }
        .legal-item { border-bottom: 0.5px solid var(--border); padding: 22px 0; }
        .legal-item:last-child { border-bottom: none; }
        .legal-title { font-family: var(--font-mono); font-size: 14px; font-weight: 700; color: var(--text); letter-spacing: -0.01em; margin-bottom: 8px; }
        .legal-body { font-size: 14px; color: var(--text2); line-height: 1.75; max-width: 660px; }
        .legal-link { color: var(--accent); text-decoration: none; font-family: var(--font-mono); font-size: 14px; }
        .legal-link:hover { text-decoration: underline; }
      `}</style>
    </main>
  );
}
